provider:
  host:  https://localhost:9443 #Change the host
client:
  client-id: ul8_Wtg8ryKWQbaFdqM6isnZNs4a #Change client-id
  client-secret: E79rtDCepoow_YFfmLJYrEkZmA0a # Change client-secret
  post-logout-uri: http://localhost:8080/spring-boot-sample/login
  scope: openid
  authorization-grant-type: authorization_code

spring:
  security:
    oauth2:
      client:
        registration:
          wso2:
            client-name : test
            client-id: ul8_Wtg8ryKWQbaFdqM6isnZNs4a #Change client-id
            client-secret: E79rtDCepoow_YFfmLJYrEkZmA0a # Change client-secret
            authorization-grant-type: authorization_code
            scope: openId
        provider:
          wso2:
            issuer-uri: ${provider.host}/oauth2/token
  thymeleaf:
    cache: false